-- ALTER TABLE
CREATE TABLE MyTable16
(
	id INT,
    title VARCHAR(255),
    body VARCHAR(255)
);

-- ADD COLUMN
ALTER TABLE MyTable16
ADD inserted TIMESTAMP;

DESC MyTable16;

-- DROP COLUMN
ALTER TABLE MyTable16
DROP COLUMN inserted;

-- MODIFY COLUMN
ALTER TABLE MyTable16
MODIFY COLUMN body VARCHAR(1023);

-- ADD NOT NULL
ALTER TABLE MyTable16
MODIFY title VARCHAR(255) NOT NULL;

-- UPDATE
INSERT INTO MyTable16
(id, title)
VALUES
(1, 'title1');

SELECT * FROM MyTable16;

ALTER TABLE MyTable16
MODIFY body VARCHAR(1023) NOT NULL;

UPDATE MyTable16
SET body = ''
WHERE body IS NULL;

-- ADD UNIQUE
ALTER TABLE MyTable16
ADD UNIQUE (id);

DESC MyTable16;

-- ADD PRIMARY KEY
ALTER TABLE MyTable16
ADD PRIMARY KEY (id);

-- DROP PRIMARY KEY
ALTER TABLE MyTable16
DROP PRIMARY KEY;

-- MODIFY AUTO_INCREMENT
ALTER TABLE MyTable16
MODIFY id INT PRIMARY KEY AUTO_INCREMENT;
